In [1]:
import pandas as pd
import sklearn

labeledData = pd.read_csv(r'Data/LabelData.csv')
labeledData.head(10)

,user_id,age,male,friend_cnt,avg_friend_age,avg_friend_male,friend_country_cnt,subscriber_friend_cnt,songsListened,lovedTracks,...,delta_subscriber_friend_cnt,delta_songsListened,delta_lovedTracks,delta_posts,delta_playlists,delta_shouts,tenure,good_country,delta_good_country,adopter
0,10,24,0,20,26.333333,0.777778,6,0,37804,4,...,0,54,0,0,0,0,79,0,0,0
1,58,29,1,12,26.900000,0.818182,6,1,15955,19,...,0,802,0,0,0,1,80,0,0,0
2,72,22,0,4,21.000000,1.000000,2,0,31441,7,...,0,0,0,0,0,0,53,0,0,0
3,121,27,0,1,29.000000,1.000000,1,0,0,0,...,0,0,0,0,0,0,59,0,0,0
4,137,22,1,4,21.250000,0.750000,1,0,774,0,...,0,0,0,0,0,0,60,0,0,0
5,261,21,1,2,23.000000,0.500000,1,0,5098,0,...,0,0,0,0,0,0,59,0,0,0
6,270,18,1,27,23.473684,0.500000,12,0,84287,5,...,0,0,0,0,0,0,59,0,0,0
7,281,23,1,21,28.400000,0.687500,9,2,16498,0,...,0,0,0,0,0,0,60,0,0,0
8,320,23,1,5,25.500000,0.800000,1,1,14823,1,...,0,0,0,0,0,0,59,0,0,0
9,322,21,1,2,24.000000,0.500000,1,0,12643,0,...,0,0,0,0,0,0,68,0,0,0

# Exploratory Data Analysis (EDA)

- Analyze the data to gain insights into the relationships between different features and the target variable (adopter).
- Plot histograms, boxplots, and scatterplots to visualize the data distribution and identify potential outliers.